export const USERS = [
    {
        id: 1,
        handle: 'bobbrown',
        name: 'Bob Brown',
        email: 'bob.brown@example.com',
        access: 'Owner',
        role: 'Co-Founder / CEO',
        avatarUrl: 'https://avatars.githubusercontent.com/u/2?v=4',
        online: true,
        initials: '',
    },
    {
        id: 2,
        handle: 'charliewhite',
        name: 'Charlie White',
        email: 'charlie.white@example.com',
        access: 'Admin',
        role: 'Co-Founder / CTO',
        avatarUrl: 'https://avatars.githubusercontent.com/u/1?v=4',
        online: false,
        initials: '',
    },
    {
        id: 3,
        handle: 'johndoe',
        name: 'John Doe',
        email: 'john.doe@example.com',
        access: 'Admin',
        role: 'Administrator',
        avatarUrl: 'https://avatars.githubusercontent.com/u/3?v=4',
        online: true,
        initials: 'jd',
    },
    {
        id: 4,
        handle: 'janesmith',
        name: 'Jane Smith',
        email: 'jane.smith@examle.com',
        access: 'User',
        role: 'Editor',
        avatarUrl: 'https://avatars.githubusercontent.com/u/4?v=4',
        online: false,
        initials: 'js',
    },
    {
        id: 5,
        handle: 'alicejohnson',
        name: 'Alice Johnson',
        email: 'alice.johnson@example.com',
        access: 'Guest',
        role: 'Viewer',
        avatarUrl: 'https://avatars.githubusercontent.com/u/5?v=4',
        online: true,
        initials: 'aj',
    },
    {
        id: 6,
        handle: 'dianagreen',
        name: 'Diana Green',
        email: 'diana.green@example.com',
        access: 'User',
        role: 'Contributor',
        avatarUrl: 'https://avatars.githubusercontent.com/u/6?v=4',
        online: false,
        initials: '',
    },
    {
        id: 7,
        handle: 'ethanblue',
        name: 'Ethan Blue',
        email: 'ethan.blue@example.com',
        access: 'Guest',
        role: 'Subscriber',
        avatarUrl: 'https://avatars.githubusercontent.com/u/7?v=4',
        online: true,
        initials: '',
    }
];

export const PLAYERS = [
    { rank: 1, name: 'Connor McDavid', position: 'C', gamesPlayed: 56, goals: 30, assists: 45, points: 75, plusMinus: 20 },
    { rank: 2, name: 'Auston Matthews', position: 'C', gamesPlayed: 58, goals: 28, assists: 40, points: 68, plusMinus: 15 },
    { rank: 3, name: 'Nathan MacKinnon', position: 'C', gamesPlayed: 55, goals: 25, assists: 42, points: 67, plusMinus: 18 },
    { rank: 4, name: 'Leon Draisaitl', position: 'C', gamesPlayed: 57, goals: 27, assists: 38, points: 65, plusMinus: 16 },
    { rank: 5, name: 'Sidney Crosby', position: 'C', gamesPlayed: 59, goals: 24, assists: 41, points: 65, plusMinus: 14 },
    { rank: 6, name: 'Alex Ovechkin', position: 'LW', gamesPlayed: 60, goals: 32, assists: 30, points: 62, plusMinus: 12 },
    { rank: 7, name: 'Patrick Kane', position: 'RW', gamesPlayed: 58, goals: 22, assists: 35, points: 57, plusMinus: -5 },
    { rank: 8, name: 'Brad Marchand', position: 'LW', gamesPlayed: 56, goals: 20, assists: 36, points: 56, plusMinus: -2 },
    { rank: 9, name: 'Steven Stamkos', position: 'C', gamesPlayed: '57', goals: '21', assists: '34', points: '55', plusMinus: '-3' },
    { rank: '10', name: 'Mark Scheifele', position: 'C', gamesPlayed: '59', goals: '19', assists: '35', points: '54', plusMinus: '-4' },
];

export const COUNTRIES = [
    { code: 'CA', name: 'Canada' },
    { code: 'US', name: 'United States' },
    { code: 'MX', name: 'Mexico' }
]

export const SOLID_COLOR_20 = [
    'dark/zinc', 'dark/white',
    'dark', 'zinc', 'white', 'red', 'orange',
    'amber', 'yellow', 'lime', 'green', 'emerald',
    'teal', 'cyan', 'sky', 'blue', 'indigo',
    'violet', 'purple', 'fuchsia', 'pink', 'rose'];